import type { AgentInfo, Inquiry, PropertyData, TourBooking, WhatsAppCampaign, WhatsAppTemplate } from './types.js';

export const INITIAL_PROPERTIES: PropertyData[] = [
  {
    id: 'prop-1',
    title: 'Greenwood Heritage Bungalow',
    slug: 'greenwood-heritage-bungalow',
    price: 48500000,
    formattedPrice: '₹4.85 Cr',
    type: 'Single Family',
    status: 'For Sale',
    location: 'Plot 14, Koregaon Park, Pune, Maharashtra',
    city: 'Pune',
    state: 'MH',
    zip: '411001',
    beds: 4,
    baths: 4,
    sqft: 3600,
    yearBuilt: 2022,
    description:
      'An architectural tour de force nestled in the heritage tree canopies of Koregaon Park. Featuring Burma teak accents, Italian Statuario marble, open-concept chef kitchen with premium German appliances, expansive private veranda, and landscaped Zen water garden.',
    features: [
      'Bespoke Italian Statuario Marble Floors',
      'Burma Teak Wood Fenestration',
      'Solar Rooftop Grid with EV Charger',
      'Daikin VRV Central Climate Control',
      'Primary Suite with Jacuzzi & Rain Shower',
      'Landscaped Garden with Private Lap Pool',
    ],
    images: [
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    ],
    isFeatured: true,
    hoaMonthly: 12000,
    propertyTaxAnnual: 95000,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'prop-2',
    title: 'Parkside Modern Haven',
    slug: 'parkside-modern-haven',
    price: 85000000,
    formattedPrice: '₹8.50 Cr',
    type: 'Villa',
    status: 'For Sale',
    location: 'DLF Phase 5, Golf Course Road, Gurgaon, Haryana',
    city: 'Gurgaon',
    state: 'HR',
    zip: '122002',
    beds: 5,
    baths: 5.5,
    sqft: 4800,
    yearBuilt: 2023,
    description:
      'A masterclass in contemporary luxury architecture along the prestigious Golf Course Road corridor. Double-height triple-glazed glass facades effortlessly dissolve boundaries between curated interiors and verdant private lawns. Features Lutron smart lighting, Poggenpohl kitchen, and private basement entertainment lounge.',
    features: [
      'Double-Height Glass Facade overlooking Green Belt',
      'German Poggenpohl Custom Culinary Suite',
      'Lutron Home Automation & Touch Control',
      'Private High-Speed Schindler Home Elevator',
      'Courtyard with Floating Fire Table',
      'Climate-Controlled 350-Bottle Wine Cellar',
    ],
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    ],
    isFeatured: true,
    hoaMonthly: 18500,
    propertyTaxAnnual: 145000,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'prop-3',
    title: 'Marine Drive Arabian Sea Penthouse',
    slug: 'marine-drive-sea-penthouse',
    price: 185000000,
    formattedPrice: '₹18.50 Cr',
    type: 'Penthouse',
    status: 'For Sale',
    location: 'Marine Drive Promenade, Churchgate, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'MH',
    zip: '400020',
    beds: 4,
    baths: 4.5,
    sqft: 5200,
    yearBuilt: 2023,
    description:
      "Crown-jewel 34th-floor sky residence boasting unobstructed 270-degree panoramic vistas of the Queen's Necklace and the Arabian Sea. Includes direct biometric high-speed elevator access, 1,800 sq ft private viewing terrace with infinity plunge pool, Boffi custom kitchen, and 24/7 five-star white-glove concierge.",
    features: [
      "Unobstructed Panoramic Arabian Sea & Queen's Necklace Views",
      '1,800 sq ft Private Rooftop Terrace & Plunge Pool',
      'Biometric Direct High-Speed Elevator Access',
      'Boffi Kitchen with Sub-Zero & Miele Appliances',
      'Master Spa Suite with Hydrotherapy Tub',
      'Four Dedicated Automated Basement Parking Bays',
    ],
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    ],
    isFeatured: true,
    hoaMonthly: 42000,
    propertyTaxAnnual: 280000,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'prop-4',
    title: 'Casa Sol Oceanfront Portuguese Villa',
    slug: 'casa-sol-oceanfront-villa',
    price: 127500000,
    formattedPrice: '₹12.75 Cr',
    type: 'Villa',
    status: 'For Sale',
    location: 'Assagao Badem Road, Assagao, North Goa',
    city: 'Goa',
    state: 'GA',
    zip: '403507',
    beds: 4,
    baths: 5.0,
    sqft: 4500,
    yearBuilt: 2024,
    description:
      'Sensitively restored Indo-Portuguese luxury estate amidst coconut groves and swaying palms in high-fashion Assagao. Features exposed laterite stone arches, double-height vaulted timber ceilings, 20-meter infinity pool, shaded cabanas, and detached staff quarters.',
    features: [
      'Restored Indo-Portuguese Architectural Heritage',
      '20-Meter Private Heated Saltwater Infinity Pool',
      'Open-Air Courtyard Dining with Pizza Oven',
      'Off-Grid Capable Solar Power & Battery System',
      'Separate Two-Bedroom Detached Staff Quarters',
      'Lush 1.2 Acre Gated Tropical Estate',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
    ],
    isFeatured: true,
    hoaMonthly: 15000,
    propertyTaxAnnual: 85000,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'prop-5',
    title: 'The Luminary Worli Sky Penthouse',
    slug: 'the-luminary-worli-penthouse',
    price: 350000,
    formattedPrice: '₹3,50,000/mo',
    type: 'Penthouse',
    status: 'For Rent',
    location: 'Worli Sea Face Promenade, Worli, Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'MH',
    zip: '400018',
    beds: 3,
    baths: 3.5,
    sqft: 2800,
    yearBuilt: 2023,
    description:
      'Ultra-luxury sky residence for lease in an iconic tower on Worli Sea Face. Features direct elevator access into an art gallery foyer, wraparound sea-view deck facing Bandra-Worli Sea Link, Italian Poliform kitchen, and membership to the tower\u2019s clubhouse and rooftop sky lounge.',
    features: [
      'Direct Private High-Speed Elevator Access',
      'Sea Link & Arabian Sea Sunset Panoramas',
      'Fully Furnished with Imported Italian Decor',
      'Tower Clubhouse with Olympic Pool & Spa',
      '24/7 Security, Valet, & Concierge Desk',
    ],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    ],
    isFeatured: false,
    hoaMonthly: 25000,
    propertyTaxAnnual: 110000,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'prop-6',
    title: 'Nilgiri Granite Architectural Residence',
    slug: 'nilgiri-granite-architectural-residence',
    price: 62000000,
    formattedPrice: '₹6.20 Cr',
    type: 'Single Family',
    status: 'For Sale',
    location: 'Road No. 36, Jubilee Hills, Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'TS',
    zip: '500033',
    beds: 4,
    baths: 4.5,
    sqft: 3950,
    yearBuilt: 2023,
    description:
      'Sculptural contemporary estate built with raw Nilgiri granite and charred cedar in prime Jubilee Hills. Designed to harness natural wind tunnels for passive cooling, centered around an indoor water courtyard with open skylights and views towards KBR National Park.',
    features: [
      'IGBC Platinum Green Building Certified',
      'Bespoke Hand-Chiseled Nilgiri Granite Facade',
      'Central Rainwater Harvesting Courtyard',
      '11-Seat Dolby Atmos Private Home Theatre',
      'Cantilevered Teak Wood Floating Staircase',
      'Three Covered Automated Basement Car Parks',
    ],
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    ],
    isFeatured: true,
    hoaMonthly: 12000,
    propertyTaxAnnual: 92000,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const INITIAL_TOUR_BOOKINGS: TourBooking[] = [
  {
    id: 'TR-00101',
    propertyId: 'prop-3',
    propertyTitle: 'Marine Drive Arabian Sea Penthouse',
    tourType: 'In-Person',
    date: '2026-09-22',
    time: '11:00 AM',
    name: 'Aditya Singhania',
    email: 'aditya.s@singhaniaholdings.com',
    phone: '+91 98200 11223',
    notes: 'Requires 4 parking spaces and private elevator keycard access.',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'TR-00102',
    propertyId: 'prop-4',
    propertyTitle: 'Casa Sol Oceanfront Portuguese Villa',
    tourType: 'Live Video Walkthrough',
    date: '2026-09-24',
    time: '04:30 PM',
    name: 'Vikramaditya Roy',
    email: 'v.roy@techcapital.in',
    phone: '+91 98111 88990',
    notes: 'Virtual walkthrough requested while traveling abroad in London.',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 14 * 3600000).toISOString(),
  },
  {
    id: 'TR-00103',
    propertyId: 'prop-2',
    propertyTitle: 'Parkside Modern Haven',
    tourType: 'In-Person',
    date: '2026-09-19',
    time: '02:00 PM',
    name: 'Dr. Meera Nambiar',
    email: 'meera.n@apollohealth.org',
    phone: '+91 98450 33445',
    notes: 'Interested in structural vastu and private lawn orientation.',
    status: 'completed',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'INQ-00101',
    name: 'Rajesh & Ananya Dalal',
    email: 'rajesh.dalal@dalalwealth.com',
    phone: '+91 98202 44556',
    interestType: 'buying',
    preferredLocation: 'Worli / Marine Drive, Mumbai',
    budgetRange: '₹15 Cr - ₹25 Cr',
    message: 'Seeking an uninterrupted sea-view penthouse with at least 4 car parks and direct high-speed elevator access.',
    status: 'contacted',
    notes: 'Sent brochure for Marine Drive Penthouse. Follow-up scheduled for Friday.',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'INQ-00102',
    name: 'Rajiv Menon (NRI - UK)',
    email: 'rmenon@mayfairadvisors.co.uk',
    phone: '+44 7700 900123',
    interestType: 'investment',
    preferredLocation: 'Assagao / Siolim, North Goa',
    budgetRange: '₹10 Cr - ₹15 Cr',
    message: 'Looking for a private heritage villa with pool for family vacations and luxury holiday rental yields.',
    status: 'pending',
    notes: '',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'INQ-00103',
    name: 'Sunita Kothari',
    email: 'sunita.k@kotharigroup.com',
    phone: '+91 98300 77889',
    interestType: 'selling',
    preferredLocation: 'Koregaon Park, Pune',
    budgetRange: '₹5 Cr+',
    message: 'Interested in listing our 4,200 sqft ancestral bungalow with LuxeLiving for exclusive off-market placement.',
    status: 'negotiating',
    notes: 'Valuation report prepared. Meeting at Pune club next Monday.',
    createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
];

export const INITIAL_NEWSLETTER: string[] = [
  'vip-buyer@luxeliving.in',
  'hni-investor@singaporecapital.sg',
  'arjun.kapoor@familyoffice.in',
  'kavita.deshmukh@alturagroup.com',
];

export const INITIAL_AGENT: AgentInfo = {
  name: 'Priya Sharma',
  role: 'Managing Principal & Ultra-Luxury Property Specialist',
  experienceYears: 12,
  rank: 'Top 1% Luxury Producer in India',
  salesVolume: '₹850+ Cr Sales Volume',
  bio: 'With over 12 years of leadership in India\u2019s ultra-prime residential market, Priya advises HNI families, tech founders, and NRI investors. Her advisory combines proprietary data-driven valuation models with absolute discretion and personalized concierge representation.',
  fullBio:
    'Priya Sharma has orchestrated over ₹850 Crore in residential transactions across premier locations in Mumbai (Worli, Bandra, Marine Drive), Delhi NCR (Golf Course Road, Lutyens\u2019 Delhi), Goa, and Bengaluru. Regularly featured in economic dailies as an authority on Indian luxury housing trends, Priya brings institutional-grade due diligence, MahaRERA compliance expertise, and bespoke off-market access to every client mandate.',
  image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
  phone: '+91 98201 54321',
  email: 'priya.sharma@luxeliving.in',
  licenseNumber: 'MahaRERA Reg. #A51900028491',
  specialties: [
    'Seafront Penthouses & Duplexes',
    'Private Gated Villas & Estates',
    'Discreet Off-Market Acquisitions',
    'NRI Investment & Wealth Advisory',
    'MahaRERA & Legal Due Diligence',
  ],
};

export const WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-01',
    title: 'Off-Market Penthouse Launch',
    category: 'Off-Market Launch',
    description: 'Private announcement for high-ticket sea-facing penthouses and sky duplexes.',
    body: 'Namaste {name},\n\nWe have secured an exclusive, off-market opportunity at *{property_title}*, located in {city}.\n\n*Key Highlights:*\n\u2726 Valued at: *{property_price}*\n\u2726 Architecture: Private Sky Deck & Panoramic Views\n\u2726 Compliance: MahaRERA Verified\n\nAs this residence is strictly confidential and not listed on public aggregators, we are extending first access to our private circle.\n\nWould you like me to send the confidential portfolio brochure or schedule a discreet walkthrough?\n\nWarm regards,\n*{agent_name}*\nLuxeLiving Private Office\n{booking_link}',
  },
  {
    id: 'tpl-02',
    title: 'Private Showing & High-Tea RSVP',
    category: 'Private Viewing',
    description: 'Invitation for an intimate weekend walkthrough with the lead advisor.',
    body: "Dear {name},\n\nYou are cordially invited to an exclusive private viewing and architectural walkthrough of *{property_title}* in {city}.\n\n\ud83d\udcc5 This Saturday & Sunday\n\ud83d\udccd {property_location}\n\ud83c\udff7\ufe0f Valued at: *{property_price}*\n\nOur Managing Principal, *{agent_name}*, will personally host you with complete privacy.\n\nPlease reply with *'RSVP'* or tap the link below to reserve your private appointment slot:\n{booking_link}",
  },
  {
    id: 'tpl-03',
    title: 'NRI Wealth & High-Yield Luxury Alert',
    category: 'NRI Investment',
    description: 'Tailored for NRI investors in Dubai, Singapore, London, and US seeking prime Indian real estate.',
    body: "Hello {name},\n\nRegarding your interest in prime luxury investments in India within the *{budget}* bracket:\n\nWe are presenting a curated trophy asset: *{property_title}* ({city}).\n\n\u2726 Projected Rental Yield: Top-tier expat & corporate lease\n\u2726 Capital Appreciation: 14-18% YoY micro-market trend\n\u2726 Repatriation & FEMA advisory assistance fully supported\n\nConfidential brochure & ROI dossier available on request. Let us know if you'd like a virtual 3D tour via Zoom/Google Meet.\n\nBest regards,\n*{agent_name}* | LuxeLiving India\n{booking_link}",
  },
  {
    id: 'tpl-04',
    title: 'Festive Privilege / New Phase Allocation',
    category: 'Festival Privilege',
    description: 'Limited festive release for VIP clientele before general market price escalations.',
    body: "Greetings {name},\n\nTo celebrate this festive season, the developer has opened a restricted VIP tranche of premier residences at *{property_title}* in {city}.\n\n\ud83c\udf1f Exclusive VIP Pricing: *{property_price}*\n\ud83c\udf1f Bespoke Italian interior design package included\n\ud83c\udf1f Priority floor selection\n\nOnly 3 residences remaining under this allocation. Reply *'INFO'* or connect directly at {booking_link} to lock your preview.",
  },
];

export const INITIAL_WHATSAPP_CAMPAIGNS: WhatsAppCampaign[] = [];
